### ISSUE TITLE
Any chances to have this compiled for Linux?

### ISSUE THREAD

**Issue by darderik** [maca134/armaext#1]
I just discovered this awesome extension,and I was wondering if maybe it would be possible to port this to Linux,maybe using Mono or similiars.

I know that maybe the project could be abandoned , but it'd be awesome to have this on linux.

Thank you.

**Comment by maca134** [comment]
Not abandoned but i have found anything else that needs adding. I use this quite abit

**Comment by darderik** [comment]
Got it. 
Btw, i tried to compile this on linux but ,as the extension is using windows.h libraries,the build failed.
I'd be glad to be kept updated on this,as a so useful extension would make things easier.

Thank you.
